# Generated by Django 4.2.5 on 2023-09-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_article_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.ImageField(
                default="static/logos/cinema_logo.png", upload_to="static/articles"
            ),
        ),
    ]
