# Generated by Django 4.2.5 on 2023-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("job_role", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=12)),
                ("email_address", models.EmailField(max_length=254)),
            ],
        ),
    ]
