# Generated by Django 4.2.5 on 2023-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="photo",
            field=models.ImageField(
                default="static/logos/cinema_logo.png", upload_to="static/staff"
            ),
        ),
    ]
