# Generated by Django 4.2.5 on 2023-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0003_mapdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapdata",
            name="date",
            field=models.DateField(verbose_name="date_add"),
        ),
    ]
